### ISSUE TITLE
Better citations layout for syllabus

### ISSUE THREAD

**Issue by BBieri** [jhollway/iheiddown#100]

**Comment by BBieri** [comment]
I added a neat lua filter allowing users to color the text of the syllabus with `xcolor` (latex colors). This allows users to distinguish between optional and mandatory readings.

I also added an optional "bibimport" section in the YAML header should instructors wish to share the bibfiles they are using to generate the syllabus. This would be a sizeable gain of time for students since they would be able to just import it in their bibliography manager and automatically download the corresponding PDFs.

Let me know what you think of these improvements @jhollway .

**Comment by jhollway** [comment]
These sound amazing @BBieri . I look forward to testing them when I get a chance.
