### ISSUE TITLE
index document failing convert despite updating biber

### ISSUE THREAD

**Issue by ravinagori** [jhollway/iheiddown#105]
**Describe the bug**
Downloaded the existing version and tried to compile it in R studio. The following error shows up

Rendering book in directory '.'
  |..                                                                    |   3%
   inline R code fragments

  |....                                                                  |   5%
label: unnamed-chunk-1 (with options) 

processing file: _main.Rmd
List of 1
 $ include: logi FALSE

  |.....                                                                 |   8%
   inline R code fragments

  |.......                                                               |  10%
label: chunk-parts (with options) 
List of 4
 $ results  : chr "asis"
 $ echo     : logi FALSE
 $ fig.cap  : chr "Chunk parts"
 $ out.width: chr "\\textwidth"

  |.........                                                             |  13%
  ordinary text without R code

  |...........                                                           |  15%
label: load_pkgs (with options) 
List of 1
 $ message: logi FALSE

  |.............                                                         |  18%
  ordinary text without R code

  |..............                                                        |  21%
label: iheidlogo (with options) 
List of 3
 $ fig.cap  : chr "IHEID logo"
 $ out.width: chr "50%"
 $ fig.align:
Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

 chr "center"

  |................                                                      |  23%
  ordinary text without R code

  |..................                                                    |  26%
label: subd (with options) 
List of 2
 $ fig.cap  : chr "Subdiv. graph"
 $ out.extra: chr "scale=0.75"

  |....................                                                  |  28%
  ordinary text without R code

  |......................                                                |  31%
label: subd2 (with options) 
List of 3
 $ out.extra: chr "angle=180, scale=1.1"
 $ fig.scap : chr "Subdiv. graph flipped"
 $ fig.cap  : chr "A Larger Figure, Flipped Upside Down"

  |.......................                                               |  33%
  ordinary text without R code

  |.........................                                             |  36%
label: cars
  |...........................                                           |  38%
  ordinary text without R code

  |.............................                                         |  41%
label: load_data
  |...............................                                       |  44%
  ordinary text without R code

  |................................                                      |  46%
label: str
  |..................................                                    |  49%
  ordinary text without R code

  |....................................                                  |  51%
label: view_flights (with options) 
List of 1
 $ eval: logi FALSE

  |......................................                                |  54%
  ordinary text without R code

  |.......................................                               |  56%
label: max_delays
  |.........................................                             |  59%
  ordinary text without R code

  |...........................................                           |  62%
label: maxdelays (with options) 
List of 1
 $ results: chr "asis"

  |.............................................                         |  64%
  ordinary text without R code

  |...............................................                       |  67%
label: max_props
  |................................................                      |  69%
  ordinary text without R code

  |..................................................                    |  72%
label: march3plot (with options) 
List of 2
 $ fig.height: num 3
 $ fig.width : num 6

  |....................................................                  |  74%
  ordinary text without R code

  |......................................................                |  77%
label: delaysboxplot (with options) 
List of 4
 $ warnings : logi FALSE
 $ messages : logi FALSE
 $ fig.cap  : chr "Mean Delays by Airline"
 $ fig.width: num 6

  |........................................................              |  79%
  ordinary text without R code

  |.........................................................             |  82%
label: pressure (with options) 
List of 4
 $ echo      : logi FALSE
 $ cache     : logi TRUE
 $ fig.height: num 3
 $ fig.width : num 5

  |...........................................................           |  85%
  ordinary text without R code

  |.............................................................         |  87%
label: unnamed-chunk-2
  |...............................................................       |  90%
  ordinary text without R code

  |.................................................................     |  92%
label: get-labels (with options) 
List of 1
 $ echo: logi FALSE

  |..................................................................    |  95%
  ordinary text without R code

  |....................................................................  |  97%
label: all-code (with options) 
List of 2
 $ ref.label: chr [1:17] "unnamed-chunk-1" "chunk-parts" "load_pkgs" "iheidlogo" ...
 $ eval     : logi FALSE

  |......................................................................| 100%
   inline R code fragments

/usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS _main.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output Thesis_Name_2021-08-30.tex --lua-filter /home/ravi/R/x86_64-pc-linux-gnu-library/4.1/bookdown/rmarkdown/lua/custom-environment.lua --lua-filter /home/ravi/R/x86_64-pc-linux-gnu-library/4.1/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /home/ravi/R/x86_64-pc-linux-gnu-library/4.1/rmarkdown/rmarkdown/lua/latex-div.lua --metadata-file /tmp/Rtmpj5qkpj/file249d4f06d90f --self-contained --table-of-contents --toc-depth 2 --template /home/ravi/R/x86_64-pc-linux-gnu-library/4.1/iheiddown/rmarkdown/templates/thesis_pdf/resources/template.tex --number-sections --highlight-style tango --pdf-engine xelatex --biblatex --wrap preserve --variable tables=yes --standalone -Mhas-frontmatter=false 
output file: _main.knit.md

INFO - This is Biber 2.9
INFO - Logfile is 'Thesis_Name_2021-08-30.blg'
INFO - Reading 'Thesis_Name_2021-08-30.bcf'
ERROR - Error: Found biblatex control file version 3.7, expected version 3.4.
This means that your biber (2.9) and biblatex (3.16) versions are incompatible.
See compat matrix in biblatex or biber PDF documentation.
INFO - ERRORS: 1
Error: Failed to build the bibliography via biber
Warning: LaTeX Warning: Reference `fig:chunk-parts' on page 14 undefined on input line 9
Warning: 69.
Warning: LaTeX Warning: Reference `fig:iheidlogo' on page 15 undefined on input line 104
Warning: 4.
Warning: LaTeX Warning: Reference `fig:chunk-parts' on page 16 undefined on input line 1
Warning: 052.
Warning: LaTeX Warning: Reference `fig:subd' on page 16 undefined on input line 1059.
Warning: LaTeX Warning: Reference `fig:subd2' on page 16 undefined on input line 1073.
Warning: LaTeX Warning: Reference `fig:subd' on page 16 undefined on input line 1073.
Warning: LaTeX Warning: Reference `tab:maxdelays' on page 21 undefined on input line 127
Warning: 1.
Warning: LaTeX Warning: Reference `import-data' on page 22 undefined on input line 1306.
Warning: LaTeX Warning: Reference `fig:delaysboxplot' on page 22 undefined on input line
Warning:  1323.
Warning: LaTeX Warning: Empty bibliography on input line 1609.
Warning: LaTeX Warning: There were undefined references.
Warning: LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.
Warning: Package rerunfilecheck Warning: File `Thesis_Name_2021-08-30.out' has changed.
Warning: (rerunfilecheck)                Rerun to get outlines right
Warning: (rerunfilecheck)                or use package `bookmark'.
Warning: Package biblatex Warning: Please (re)run Biber on the file:
Warning: (biblatex)                Thesis_Name_2021-08-30
Warning: (biblatex)                and rerun LaTeX afterwards.
Execution halted

**Desktop (please complete the following information):**
 - OS: [ubuntu 18.04]
 - R Version [e.g. 4.4.1]
 - RStudio Version [if applicable]

**Additional context**
In the local system, however, running biber --version shows 
biber version: 2.16

**Comment by ravinagori** [comment]
a fresh install of texlive, i.e. deleting all the old files and reinstalling tex-live from CTAN on the system seems to resolve this issue.

**Comment by BBieri** [comment]
Hi Ravi, 

Thanks for using `{iheiddown}` and for sharing the solution to your bug. I am sure this will be helpful down the line for users who may run into similar issues!

Have a great day!
