### ISSUE TITLE
Calling && or || with either argument of length greater than one now gives a warning (which it is intended will become an error)

### ISSUE THREAD

**Issue by jhollway** [jhollway/iheiddown#118]
Relates to the message from Brian Ripley (2022-03-22) to be fixed by 2022-04-04. Relates to `{bib2df}`.

**Comment by BBieri** [comment]
The issue stems from the `fix_bib()` function which uses the `df2bib()` function which in turn uses the problematic double logical operators. I've prepared a PR for them to get it fixed and have temporarily commented out `fix_bib()`.  This should resolve the CRAN issue.
