### ISSUE TITLE
Error to generate PDF

### ISSUE THREAD

**Issue by carlosbgueiros** [jhollway/iheiddown#13]
**Describe bug 1**
The following message appears:
Error: Input files not all in same directory, please supply explicit wd
The problem seems to be with Bookdown 0.20

The solution is discussed here:
https://stackoverflow.com/questions/62578811/error-input-files-not-all-in-same-directory-please-supply-explicit-wd

To solve the problem I just used a Rprofile in the same folder as index.Rmd with the following command:
`options(bookdown.render.file_scope = FALSE)`

**Describe bug 2 (related)** 
 After using the Rprofile the pdf is generated but with the following error in the console:

Translated and Original, respectively:
> Error in merge_lists(as.list(formals(format_function)), format$options,  : 
  argument "base" missing, no standard
> Error in merge_lists(as.list(formals(format_function)), format$options,  : 
  argumento "base" ausente, sem padrão

The solution was to replace this original  output options in the YAML Metadata :
`output:
  bookdown::render_book:
    input: "Untitled/Untitled.Rmd"
    output_format: iheiddown::thesis_pdf
link-citations: true
documentclass: book
`
for this output options:

`knit: "bookdown::render_book"; 
output:
  iheiddown::thesis_pdf;
link-citations: true;
documentclass: book;`

**Expected behavior**
The document is not knited and there is no pdf document.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - R Version 4.0.2
 - RStudio Version 1.3.959

**Additional context**
The Thesis {iheiddown} template was used and installed as suggested in  the README.md.

**Comment by jhollway** [comment]
Thanks for raising this @carlosbgueiros. This/these issues should be addressed now. Feel free to watch/start the repo to keep up to date with updates, and use issues to keep me/us updated with your progress.
