### ISSUE TITLE
Issues with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [jhollway/iheiddown#130]
Hi

We preparing the next release of ggplot2 and our reverse dependency checks show that your package is failing with the new version. Looking into it we see that the issues are due to our switch to using the `linewidth` aesthetic for stroke width instead of `size`. Please see https://www.tidyverse.org/blog/2022/08/ggplot2-3-4-0-size-to-linewidth/ for more info on this.

You can install the release candidate of ggplot2 using `devtools::install_github('tidyverse/ggplot2@v3.4.0-rc')` to test this out.

We plan to submit ggplot2 by the end of October and hope you can have a fix ready before then

Kind regards
Thomas

**Comment by henriquesposito** [comment]
The easiest solution, already implemented, is to change manually to ´linewidth´ and remind users to also update to a newer version of ´{ggplot2}´ (if they have not already done so). 

I am not sure just yet about what it would take to implement a more flexible solution that works for both older and newer versions of ´{ggplot2}´... Ideally, this would be a better alternative!

**Comment by thomasp85** [comment]
You can have a look at ggforce that has made changes to work with both current and future ggplot2 versions. Whether it applies to this package is hard to say but there should be some inspiration

**Comment by henriquesposito** [comment]
Will do, thank you for your help @thomasp85!
