### ISSUE TITLE
Fix bug with pkgdown website rendering

### ISSUE THREAD

**Issue by henriquesposito** [jhollway/iheiddown#131]
Pkgdown fails with a weird error...

**Comment by BBieri** [comment]
Just had a quick look at the "Build and Deploy" website action and was able to reproduce the same error locally. It seems to be related to the NAMESPACE not including the `advdate()` function from our package for some obscure reason. Redocumenting the package solved the error locally in my case. Hence, maybe adding a Document step like:

```r
- name: Document
   run: Rscript -e 'roxygen2::roxygenise()'
```
... in the `{pkgdown}` runner right above the install step might solve the issue. Hope it helps 😄
