### ISSUE TITLE
Citation style: page number in citations

### ISSUE THREAD

**Issue by valentinaIHEID** [jhollway/iheiddown#16]
I would need to add the page number in my in-text citation. 
For instance, instead of (Eising 2007), I would like (Eising 2007, p.330–31)

Is the feature already available? 

I found [this explanation on Stackoverflow](https://stackoverflow.com/questions/57928895/r-markdown-page-number-in-citations), but I don't know if the feature depends on the `csl `file, or something else.

**Comment by jhollway** [comment]
Yes, this feature is already available. Section 2.1.2 of the thesis template (i.e. chapters/02-theory.Rmd) shows you how.
