### ISSUE TITLE
Tables for pdf

### ISSUE THREAD

**Issue by valentinaIHEID** [jhollway/iheiddown#18]
I'm currently using the `tab_model` function from the `knitr `package to include my model outputs in a nicely formatted table. These are the two commands I am using (they are included in two separate chunks of code because they come from two different models): 

`tab_model(logit1, logit2, logit3, vcov.fun = "HC", vcov.type = "HC3", digits = 4,
             show.aic = T, show.loglik = T)`

`tab_model(poi1, poi2, poi3, vcov.fun = "HC", vcov.type = "HC3", digits = 4,
             show.aic = T, show.loglik = T)`

They do not seem to work when I render my paper in pdf format. What is the function I can use to wrap my model outputs in a nicely formatted table for pdf? 
It also appears that, when I render in html, only the second table works. The table from the first chunk of code blocks the rendering in html and gives an error message:

`Error in tab_model(logit1, logit2, logit3, vcov.fun = "HC", vcov.type = "HC3", digits = 4, show.aic = T, show.loglik = T) : could not find function "tab_model" Calls: <Anonymous> ... handle ->withCallingHandlers -> withVisible -> eval -> eval`

Any ideas on how I might solve this issue?

**Comment by jhollway** [comment]
Hmm, I think `sjPlot` is only for html (you'll recall that I used it in slides for the stats course that were html-based. I think `flextable` and `huxtable` are usually recommended for table construction across different outputs (see [this page](https://rfortherestofus.com/2019/11/how-to-make-beautiful-tables-in-r/)). Other options are the `stargazer`, `finalfit`, and (Liefeld's own)`texreg` packages.

**Comment by valentinaIHEID** [comment]
Ok, I'll have a look at the packages you mentioned ,thank you. If I render in html, the two `tab_model` functions should both work, but it does not seem the case.

**Comment by jhollway** [comment]
Well, the error suggests that it is not finding the function. So you might need to follow that thread... 
- [ ] Make sure you've loaded `library(sjPlot)` beforehand? 
- [ ] Make sure there aren't conflicting function names by specifying the package, e.g. `sjPlot::tab_model()`? 
- [ ] Start with the simplest working example and then successively introduce options until it breaks?
