### ISSUE TITLE
Add presentations slides template

### ISSUE THREAD

**Issue by jhollway** [jhollway/iheiddown#23]

**Comment by BBieri** [comment]
[Here](https://github.com/bquast/BeamerGeneva) is a nice beamer template we could take inspiration from.

**Comment by jhollway** [comment]
Beamer is still quite static. Nowadays there are some great markdown/html-based options in RStudio, such as those that rely on [Xaringan](https://github.com/yihui/xaringan): https://github.com/jhollway/iheidmyninja
