### ISSUE TITLE
add cite_packages() function

### ISSUE THREAD

**Issue by jhollway** [jhollway/iheiddown#26]
https://github.com/easystats/report/blob/master/R/cite_packages.R

**Comment by jhollway** [comment]
See also https://github.com/ropensci/unconf17/issues/24

**Comment by jhollway** [comment]
Try https://bookdown.org/yihui/rmarkdown-cookbook/write-bib.html

**Comment by BBieri** [comment]
### Update:

- [x] Added the function to automatically cite packages loaded while running the code chunks of the thesis. 
- [ ] Identified some more cosmetic bugs in the header when the reference section is longer than one page. In this case, the header will contain a "Chapter 6 Conclusion element"
- [ ] Identified a bug in the chapter numbering process. (for some yet obscure reason the first chapter is labeled as chapter 2)

**Comment by jhollway** [comment]
When you are ready @BBieri , you can create a PR on this

**Comment by BBieri** [comment]
@jhollway Created a draft PR for the changes but I am waiting to incorporate the last bug I spotted in the bibliography section. The header of the bibliography contains "5.Conclusion" instead of the expected "References".
