### ISSUE TITLE
Header of the bibliography section displays the name of the previous chapter

### ISSUE THREAD

**Issue by BBieri** [jhollway/iheiddown#44]
## Description:
The header of the "References" section of the thesis template displays "5.Conclusion" which is the header of the previous chapter instead of "References". Note that I was able to mitigate the issue if I defined the YAML header and the `setcounter` like in other chapters of the thesis. However, this leads to the reference being considered as "Chapter 6, References" which is not very elegant.

**Comment by BBieri** [comment]
### Update 08.01.2021 (help wanted)

Over the past few days, I have tried to apply a custom style to a single chapter in the book

**Comment by BBieri** [comment]
### Update 08.01.2021 (help wanted):

I have been trying for the past couple of days to find a way to apply custom latex styles for the different Rmd documents in the thesis project to allow for the references header to be unique to the references section. The closest I came to the desired result was to define the references section as a new chapter (just like the conclusion chapter) which alleviates the header issue.  However, this has the downside of the reference section being displayed as a chapter with a big title "Chapter 6: References" which is not desirable. 

I looked at the `{oxforddown}` documentation (the last section of [this page](https://ulyngs.github.io/oxforddown/customisations-and-extensions.html) and one related [issue](https://github.com/ulyngs/oxforddown/issues/5). Both seem to say that it is not possible to change the style of a single chapter since everything is merged into one big `.Rmd` file **before** it is knitted. This method also prevents us from using a macro that is defined in the `template.tex` file and called in the specific `.Rmd` file of the chapter by including it in the header.

*One lead I am still chasing down is to define a specific page style in the `.tex` template and apply it to the reference section.*

**Comment by jhollway** [comment]
The issue is more likely to be solved in `{bookdown}` or pandoc. See e.g. https://bookdown.org/yihui/rmarkdown-cookbook/toc-unlisted.html
