### ISSUE TITLE
Create an appendix Rmd file

### ISSUE THREAD

**Issue by BBieri** [jhollway/iheiddown#46]
Create an appendix Rmd file to dump tables, graphs, and more tables that would otherwise clutter the main corpus of the thesis.

**Comment by jhollway** [comment]
Can you write a user story about what you mean here? Something like [this](https://yihui.org/en/2018/09/code-appendix/) perhaps?

**Comment by BBieri** [comment]
Sure thing @jhollway !

There are essentially two use cases that come to my mind and that would benefit from an appendix:

1. __Transparency:__

 Users might want to highlight the code they have used to generate tables, graphs, analyses, etc.. This would increase the transparency of the work and help readers replicate the results directly. It is basically what Yihui Xie says in the post.

2. __Model selection:__

 Imagining a user who wants to forecast the closing price of an index and creates a time-series model. A significant amount of time will be spent on model selection. Having an appendix where the user can print/dump some of the discarded models would allow him to justify why he selected one model over the other without cluttering the main corpus of the text with regression tables and instead use numerical references to the various figures in the appendix.

**Comment by jhollway** [comment]
Great @BBieri , if it doesn't take you too much time to implement, do it!

**Comment by jhollway** [comment]
On the problem of how to order the appendix after the references, see https://bookdown.org/yihui/rmarkdown-cookbook/bibliography.html#include-appendix-after-bibliography
