### ISSUE TITLE
Offer option to print figures and tables at the end of the paper/chapter

### ISSUE THREAD

**Issue by jhollway** [jhollway/iheiddown#48]
http://www.texdoc.net/texmf-dist/doc/latex/preprint/figcaps.pdf

**Comment by BBieri** [comment]
This feature is already implemented with the simpler code chunks directly in Markdown. Users can display them in the appendix or at the end of the chapter by labeling them and recalling them. This might even be more computationally efficient than using an additional Latex package. 

See [this](https://bookdown.org/yihui/rmarkdown-cookbook/code-appendix.html) for more details.

I'll set up an example this afternoon in the appendix skeleton for more clarity.

**Comment by jhollway** [comment]
No, I mean printing the figures and tables at the end of the chapter (say), not just the code that creates them. This is more for (some) journal submissions though, and so is not really a current priority for `{iheiddown}`...

**Comment by jhollway** [comment]
With @BBieri decided to close this issue, as this is more for journal submission formats.
