### ISSUE TITLE
Encoding Issue on Windows

### ISSUE THREAD

**Issue by BBieri** [jhollway/iheiddown#53]
This issue is specific to Windows. It arises when the user knits the document (using the `thesis_pdf()` function of the `{iheiddown}` package. Basically, the generated Latex file by the aforementioned function and Pandoc contains badly encoded special characters such as ö ä ü from the German alphabet.

**Comment by BBieri** [comment]
It's true that French and English would work, for the most part, however, this does not take into account author names. I actually noticed it on the first few lines of the Acknowledgements section where you thank someone called "Schöpf". His "ö" takes interesting forms depending on the font that is used.

**Comment by jhollway** [comment]
So is this more a question of font choice, re #27 ?

**Comment by BBieri** [comment]
After checking the intermediary Latex file which happens to contain the weird chararcters displayed in the final PDF, the issue seems to originate when Pandoc converts RMarkdown into Latex. I'll investigate the issue further tomorrow.

**Comment by jhollway** [comment]
So is this a question of font, or font encoding? Can also try https://stackoverflow.com/questions/35671530/german-umlaut-characters-in-r-markdown

**Comment by BBieri** [comment]
@jhollway I dug a little deeper on the issue and it arises only on Windows machines and is an encoding issue. When looking at the tex file generated by the `thesis_pdf()` (or `render_book()`) function, one can see that the weirdly encoded characters are already present in the latex output. Hence this seems to be an issue either with Pandoc or the render_book function. Here is a summary of what I tried up until now: 

- I tried setting the default encoding of R-Studio to `UTF-8` and save all the files by using the "Save with encoding" option to no avail. (UTF-8 is default on MacOS while `ISO-8859-1` is on Windows).
- I tried forcing the `UTF-8` encoding in the `thesis_pdf()` function by setting `encoding = "UTF-8"` to no avail. 
- Pandoc's documentation is a little confusing since the encoding section refers to fontenc, a package that is loaded in the Latex template/header.

**Comment by jhollway** [comment]
Hmm, from the documentation it looks like `rmarkdown::render()` always assumes `encoding = "UTF-8"` anyway. Can you open the acknowledgements.Rmd file and force resave as UTF-8 somehow?

**Comment by BBieri** [comment]
Indeed, this is what puzzles me. I did save all the files using the "save with encoding" option (and specifying `UTF-8` each time) as well as setting the same encoding as default in R and setting it when using the `thesis_pdf()` function.

**Comment by BBieri** [comment]
Fixed it by saving every `R-Markdown` file in the Windows 1252 encoding instead of UTF-8.

**Comment by jhollway** [comment]
Does it still work for macOS and Linux now?

**Comment by BBieri** [comment]
It does. As a matter of fact, the only thing I did was to change the encoding with which the Rmd files are saved from UTF-8 to Windows 1252 in RStudio without changing any code whatsoever. It is a really strange error that I'll mention on the package website once it is live in a future release.
