### ISSUE TITLE
Allow users of the presentation template to reference online/installed logos

### ISSUE THREAD

**Issue by jhollway** [jhollway/iheiddown#57]

**Comment by BBieri** [comment]
Link to the blog post I used to solve this issue [here](https://www.garrickadenbuie.com/blog/xaringan-tip-logo-all-slides/).

**Comment by BBieri** [comment]
Some quick clarifications about the solution I implemented yesterday. You can set a logo on the title slide by modifying the exceptions in the script at the bottom of the HTML file adding the logos. These logos will be printed in the same spot as on the rest of the slides. Furthermore, all logos were integrated into the logo folder that is shipped with `{iheiddown}` and are already correctly formatted.

Now after reading your comment as well as some further research, I can change the solution I implemented by creating a CSS class that the user will have to mention manually on each and every slide he wants the logo to be displayed on and uploading the logos on a server (which might not be what we want if we want things to run locally) or ship them with the package. This solution has the advantage of being a bit more flexible but the main drawback is that this will be tedious (especially if the user has a lot of slides).

This second solution mostly follows [this](https://github.com/gadenbuie/xaringanExtra/issues/68) issue.

Please let me know what you think about this second solution!
