### ISSUE TITLE
Setup example bibliography for presentations

### ISSUE THREAD

**Issue by BBieri** [jhollway/iheiddown#74]
See this [wiki](https://github.com/yihui/xaringan/wiki/Bibliography-and-citations) for ways to implement it.

Don't forget to update the vignette too.

**Comment by jhollway** [comment]
Is there a way for `{xaringan}` to use `{citr}` rather than `{RefManageR }`?

**Comment by BBieri** [comment]
The issue is that `{xaringan}` does not use Pandoc to handle the Markdown files and convert them to HTML but the remark.js interpreter. This makes the use of `{citr}` impossible unfortunately as Yihui Xie pointed out [here](https://bookdown.org/yihui/rmarkdown/xaringan-format.html).

I'll try to find a more user-friendly approach to citing papers but I am afraid that we'll have to stick with inline code chunks and `{RefManageR}` for now...
