### ISSUE TITLE
Implement ninjutsu.css slide slicing tools

### ISSUE THREAD

**Issue by BBieri** [jhollway/iheiddown#80]
See [this](https://github.com/emitanaka/ninja-theme/blob/master/docs/themes/kunoichi/assets/ninjutsu.css) for more details.

**Comment by jhollway** [comment]
Looks promising! We might need to unpack or restructure the .css file soon with so many features...

**Comment by BBieri** [comment]
Agreed! I have been adding comments and keywords for advanced users to find the individual settings faster when adding features. I'll give it a try at separating the .css file into feature-centered ones before opening the next PR.
