### ISSUE TITLE
Add word count functionality

### ISSUE THREAD

**Issue by jhollway** [jhollway/iheiddown#81]

**Comment by jhollway** [comment]
@BBieri can we add functionality to count the words in the bibliography (as it would be printed) too? What other functionality might we want to develop for this function?

**Comment by jhollway** [comment]
Options could include:
- [ ] including front-matter
- [ ] including figure or table titles or captions
- [ ] including footnotes
- [ ] including the bibliography
- [ ] including appendices
- [ ] including code?

**Comment by jhollway** [comment]
@BBieri I'm moving this to Awaiting Deployment. Can you create new issues for the outstanding word count elements?

**Comment by BBieri** [comment]
Sure thing!
